//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CacheMachine.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CacheMachine.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снятая сумма.
        /// </summary>
        public static string CacheSum {
            get {
                return ResourceManager.GetString("CacheSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о карте.
        /// </summary>
        public static string CardInformation {
            get {
                return ResourceManager.GetString("CardInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта заблокирована.
        /// </summary>
        public static string CardIsBlocked {
            get {
                return ResourceManager.GetString("CardIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта не найдена.
        /// </summary>
        public static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер карты.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при попытке снятия денег.
        /// </summary>
        public static string ErrorGettingCache {
            get {
                return ResourceManager.GetString("ErrorGettingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при отображении данных о балансе.
        /// </summary>
        public static string ErrorShowingBalance {
            get {
                return ResourceManager.GetString("ErrorShowingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снятие денег.
        /// </summary>
        public static string GetCache {
            get {
                return ResourceManager.GetString("GetCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снять сумму.
        /// </summary>
        public static string GetSum {
            get {
                return ResourceManager.GetString("GetSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер карты.
        /// </summary>
        public static string InputCardNum {
            get {
                return ResourceManager.GetString("InputCardNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пин-код.
        /// </summary>
        public static string InputPinCode {
            get {
                return ResourceManager.GetString("InputPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный пин-код.
        /// </summary>
        public static string InvalidPinCode {
            get {
                return ResourceManager.GetString("InvalidPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно средств.
        /// </summary>
        public static string NotEnoughMoney {
            get {
                return ResourceManager.GetString("NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат операции.
        /// </summary>
        public static string OperationResult {
            get {
                return ResourceManager.GetString("OperationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список операций.
        /// </summary>
        public static string OperationsList {
            get {
                return ResourceManager.GetString("OperationsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остаток на счету.
        /// </summary>
        public static string RemainSum {
            get {
                return ResourceManager.GetString("RemainSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма на счету.
        /// </summary>
        public static string SumAvailable {
            get {
                return ResourceManager.GetString("SumAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр баланса.
        /// </summary>
        public static string ViewBalance {
            get {
                return ResourceManager.GetString("ViewBalance", resourceCulture);
            }
        }
    }
}
