//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CacheMachine.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CacheMachine.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache sum.
        /// </summary>
        public static string CacheSum {
            get {
                return ResourceManager.GetString("CacheSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card information.
        /// </summary>
        public static string CardInformation {
            get {
                return ResourceManager.GetString("CardInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card is blocked.
        /// </summary>
        public static string CardIsBlocked {
            get {
                return ResourceManager.GetString("CardIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card was not found.
        /// </summary>
        public static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting cache.
        /// </summary>
        public static string ErrorGettingCache {
            get {
                return ResourceManager.GetString("ErrorGettingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error showing balance.
        /// </summary>
        public static string ErrorShowingBalance {
            get {
                return ResourceManager.GetString("ErrorShowingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get cache.
        /// </summary>
        public static string GetCache {
            get {
                return ResourceManager.GetString("GetCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get sum.
        /// </summary>
        public static string GetSum {
            get {
                return ResourceManager.GetString("GetSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input card number.
        /// </summary>
        public static string InputCardNum {
            get {
                return ResourceManager.GetString("InputCardNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input pin-code.
        /// </summary>
        public static string InputPinCode {
            get {
                return ResourceManager.GetString("InputPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pin-code.
        /// </summary>
        public static string InvalidPinCode {
            get {
                return ResourceManager.GetString("InvalidPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough money.
        /// </summary>
        public static string NotEnoughMoney {
            get {
                return ResourceManager.GetString("NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation result.
        /// </summary>
        public static string OperationResult {
            get {
                return ResourceManager.GetString("OperationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations list.
        /// </summary>
        public static string OperationsList {
            get {
                return ResourceManager.GetString("OperationsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain sum.
        /// </summary>
        public static string RemainSum {
            get {
                return ResourceManager.GetString("RemainSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum available.
        /// </summary>
        public static string SumAvailable {
            get {
                return ResourceManager.GetString("SumAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized.
        /// </summary>
        public static string UserIsUnauthorized {
            get {
                return ResourceManager.GetString("UserIsUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View balance.
        /// </summary>
        public static string ViewBalance {
            get {
                return ResourceManager.GetString("ViewBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Сlear {
            get {
                return ResourceManager.GetString("Сlear", resourceCulture);
            }
        }
    }
}
